export enum PersonalityType {
  OUTGOING = 'OUTGOING',
  QUIET = 'QUIET',
  CARING = 'CARING',
  LEADER = 'LEADER',
  HUMOROUS = 'HUMOROUS',
  EMOTIONAL = 'EMOTIONAL',
  ADVENTUROUS = 'ADVENTUROUS',
  PLANNER = 'PLANNER',
  SPONTANEOUS = 'SPONTANEOUS',
}

export enum DatingStyle {
  PROACTIVE = 'PROACTIVE',
  AFFECTIONATE = 'AFFECTIONATE',
  FRIENDLY = 'FRIENDLY',
  TSUNDERE = 'TSUNDERE',
  ATTENTIVE = 'ATTENTIVE',
  RESERVED_BUT_CARING = 'RESERVED_BUT_CARING',
  FREE_SPIRITED = 'FREE_SPIRITED',
  FREQUENT_CONTACT = 'FREQUENT_CONTACT',
}

export enum LifestyleType {
  MORNING_PERSON = 'MORNING_PERSON',
  NIGHT_PERSON = 'NIGHT_PERSON',
  HOMEBODY = 'HOMEBODY',
  TRAVELER = 'TRAVELER',
  ACTIVE = 'ACTIVE',
  GAMER = 'GAMER',
  CAFE_LOVER = 'CAFE_LOVER',
  ACTIVITY_LOVER = 'ACTIVITY_LOVER',
}

export enum DrinkingPreference {
  FREQUENTLY_OK = 'FREQUENTLY_OK',
  OCCASIONALLY_OK = 'OCCASIONALLY_OK',
  RARELY_PREFERRED = 'RARELY_PREFERRED',
  NON_DRINKER_PREFERRED = 'NON_DRINKER_PREFERRED',
  NO_PREFERENCE = 'NO_PREFERENCE',
}

export enum SmokingPreference {
  SMOKER_OK = 'SMOKER_OK',
  NON_SMOKER_PREFERRED = 'NON_SMOKER_PREFERRED',
  STRICTLY_NON_SMOKER = 'STRICTLY_NON_SMOKER',
  NO_PREFERENCE = 'NO_PREFERENCE',
}

export enum TattooPreference {
  TATTOO_OK = 'TATTOO_OK',
  SMALL_TATTOO_OK = 'SMALL_TATTOO_OK',
  NO_TATTOO_PREFERRED = 'NO_TATTOO_PREFERRED',
  NO_PREFERENCE = 'NO_PREFERENCE',
}

export enum InterestType {
  MOVIES = 'MOVIES',
  MUSIC = 'MUSIC',
  READING = 'READING',
  GAMING = 'GAMING',
  SPORTS = 'SPORTS',
  COOKING = 'COOKING',
  TRAVEL = 'TRAVEL',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  FASHION = 'FASHION',
  CAFE = 'CAFE',
  PERFORMANCE = 'PERFORMANCE',
  EXHIBITION = 'EXHIBITION',
  PETS = 'PETS',
  HIKING = 'HIKING',
  CYCLING = 'CYCLING',
}

export enum MbtiType {
  INTJ = 'INTJ',
  INTP = 'INTP',
  ENTJ = 'ENTJ',
  ENTP = 'ENTP',
  INFJ = 'INFJ',
  INFP = 'INFP',
  ENFJ = 'ENFJ',
  ENFP = 'ENFP',
  ISTJ = 'ISTJ',
  ISFJ = 'ISFJ',
  ESTJ = 'ESTJ',
  ESFJ = 'ESFJ',
  ISTP = 'ISTP',
  ISFP = 'ISFP',
  ESTP = 'ESTP',
  ESFP = 'ESFP',
}

export enum AgePreference {
  OLDER = 'OLDER',
  YOUNGER = 'YOUNGER',
  SAME_AGE = 'SAME_AGE',
  NO_PREFERENCE = 'NO_PREFERENCE',
}
